// To always get the latest diagrams, update the
// commit hash from the version merged into main
:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/wonderbird/TestProcessWrapper/fix/coverlet_with_arguments/docs

:icons: font

== Create the Test Process

=== Current Design

image::{gitplant}/current_create_process.puml[Current design of creating the test process]

The `TestProcessWrapper` stores the configuration for the target process in private members. The `Start()` method uses the `IProcessFactory` to create the process, passes all the configuration and finally starts it.

=== Problem of the Design: Command Line Arguments

The `DotnetProcessFactory` creates similar `processStartInfo` objects for the unwrapped process and for the process wrapped into `coverlet`.

It assumes that command line arguments are just appended to the `Arguments` property (string) of the processStartInfo for either the unwrapped process or the wrapped process.

IMPORTANT: This assumption is wrong. `coverlet` expects command line arguments to be appended to the test process in the `--targetargs` argument.

As a consequence, the entire command line argument handling is different for an unwrapped process and a process wrapped into `coverlet`. If we keep the current design, many `if(isCoverletEnabled) { ... } else { ... }` constructs must be used to pass arguments correctly.

=== Future Design

The `DotnetProcessFactory` is replaced by individual `ProcessBuilder` s for an unwrapped process and for a wrapped process. The specialized builders know how to handle the command line arguments.

image::{gitplant}/target_create_process.puml[Future design of creating the test process]

The constructor of `TestProcessWrapper` uses the `ProcessBuilderFactory` to get the builder matching the `isCoverletEnabled` flag.

`TestProcessWrapper` forwards the calls to `AddCommandLineArgument` and `AddEnvironmentVariable` to the `ProcessBuilder`.

When the user calls `Start()`, `TestProcessWrapper` receives the process from `ProcessBuilder.Build()` - it is either an unwrapped process or a process wrapped into coverlet. The implementation of `Build()` in the derived classes can handle the command line arguments correctly for their specific case.