@startuml
allowmixing

actor "Library User" as user

class "TestProcessWrapper" as wrapper {
  - Dictionary<string, string> _arguments
  - Dictionary<string, string> _environmentVariables
  - UnwrappedProcessBuilder _testProcessBuilder
  - ITestProcess _process
  + BuildConfiguration BuildConfiguration
  + bool IsCoverletEnabled

  + AddCommandLineArgument(...)
  + AddEnvironmentVariable(...)
  + Start()
}

user -- wrapper : interact\nonly with >

class "UnwrappedProcessBuilder" as builder {
  + constructor(appProjectName)
  + AddCommandLineArguments(...)
  + AddEnvironmentVariables(...)
  + Build()
}

wrapper *-- builder : _testProcessBuilder

interface "ITestProcess" as process_if {
  + Start()
}

wrapper *- process_if : _process

class "TestProcess" as process
process_if <|-- process

builder -> process : create >

note bottom of builder
if (!_isCoverletEnabled)
{
    processStartInfo = CreateProcessStartInfo("dotnet", _testProjectInfo.AppDllName);
}
else
{
    processStartInfo = CreateProcessStartInfoWithCoverletWrapper();
}
end note
@enduml