@startuml
allowmixing

actor "Library User" as user

class "TestProcessWrapper" as wrapper {
  - IProcessFactory _testProcessBuilder
  + AddCommandLineArgument(...)
  + AddEnvironmentVariable(...)
  + EnableCoverlet()
  + SelectBuildConfiguration(...)
  + Start()
}

user -- wrapper : interact\nonly with >

interface "IProcessFactory" as builder_if
builder_if : Create()

class "TestProcessBuilder" as builder

interface "ITestProcess" as process_if {
  + AddCommandLineArgument(...)
  + AddEnvironmentVariable(...)
  + Start()
}

class "TestProcess" as process

builder_if <|-- builder
process_if <|-- process

builder_if -> process_if :  create >
builder -> process : create >

wrapper *- builder_if

wrapper::Start --> builder_if::Create

note bottom of builder
if (!_isCoverletEnabled)
{
    processStartInfo = CreateProcessStartInfo("dotnet", _testProjectInfo.AppDllName);
}
else
{
    processStartInfo = CreateProcessStartInfoWithCoverletWrapper();
}
end note
@enduml