@startuml
allowmixing

actor "Library User" as user

class "TestProcessWrapper" as wrapper {
  - TestProcessBuilder _testProcessBuilder
  - ITestProcess _process
  + AddCommandLineArgument(...)
  + AddEnvironmentVariable(...)
  + EnableCoverlet()
  + SelectBuildConfiguration(...)
  + Start()
}

user -- wrapper : interact\nonly with >

class "TestProcessBuilder" as builder {
  + Build()
}

wrapper *-- builder : _testProcessBuilder

interface "ITestProcess" as process_if {
  + AddCommandLineArgument(...)
  + AddEnvironmentVariable(...)
  + Start()
}

wrapper *- process_if : _process

class "TestProcess" as process
process_if <|-- process

builder -> process : create >

note bottom of builder
if (!_isCoverletEnabled)
{
    processStartInfo = CreateProcessStartInfo("dotnet", _testProjectInfo.AppDllName);
}
else
{
    processStartInfo = CreateProcessStartInfoWithCoverletWrapper();
}
end note
@enduml